# Generated by Django 5.2.15 on 2026-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_budgetproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['-year', 'code'],
            },
        ),
    ]
