# Generated by Django 5.2.15 on 2026-06-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0004_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='budgeting.budget')),
                ('budget_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='budgeting.budgetproduct')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='budgeting.costcenter')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='budgeting.funding')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('budget', 'cost_center', 'funding', 'budget_product'), name='unique_budget_line')],
            },
        ),
    ]
