# Generated by Django 5.2.15 on 2026-06-24 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_budgetline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('budget_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailed_products', to='budgeting.budgetproduct')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
