# Generated by Django 5.2.15 on 2026-06-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_budget_is_active'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.costcenter')),
                ('detailed_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='budgeting.detailedproduct')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgeting.funding')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaserequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
